<?php include'header.php'?>


<div class="container">
<div class="row"></div>


<div class="row">
<div class="col-md-4 returnspolicy">
<h2 class="returnspolicy">Returns<br> and refunds</h2> 
</div>

<div class="col-md-4 returnspolicy">


<br>
<br>
<br>
<br>
<h1></h1>
<p>Thank you for shopping at Rockoutrecords.</p>

<p>If you are not entirely satisfied with your purchase, we're here to help.</p>

<p>Our products can be returned within 60 days of the original purchase of the product.</p>

<p>Before you return a product, please make sure that:</p>

<ul>
    <li>The product was purchased in the last 60 days</li>
    <li>The product is in its original packaging</li>
</ul>

<p>Send the product with its original packing to:</p>

<p>70-72 Portland Street<br />
Manchester M1 4GU</p>

<p><strong>Shipping charges</strong></p>
<p>Shipping charges incurred in connection with the return of a product are refundable.</p>

<p><strong>Damaged items</strong></p>
<p>If you received a damaged product, please notify us immediately for assistance.</p>

<p><strong>Sale items</strong></p>
<p>Unfortunately, sale items cannot be refunded. Only regular price items can be refunded.</p>



<p><strong>Contact us</strong>
<p>If you have any questions about our Returns and Refunds Policy, please contact us:</p>

<ul>
    
    <li>By email: colin_andersonx360@live.co.uk</li>
    
</ul>

<p class="returnspolicy">Our Return and Refund Policy was generated by <a class="returnspolicy" href="https://termsfeed.com/return-refund-policy/generator/">TermsFeed Return Policy Generator</a>.</p>








</p>
<br>
 <a class="returnspolicy" href="index.php"> return to the website </a>




</div>



</div>
<div class="col-md-4"></div>
<div class="col-md-4"></div>













</div>
</div>

<div class="row">


<div class="col-md-12">

<?php include'footer.php'?>
</div>



</div>